### ISSUE TITLE
프로그램 개발/보안/비밀번호 암호화 : 작성하기

### ISSUE THREAD

**Issue by hsh2001** [tmdgus0084/kor-law-for-dev#1]
도움 주실 수 있다면 환영입니다! 많은 도움 부탁드립니다.  코멘트 남겨주세요.

TODO:
- [x]  암호화란?
- [x] 비밀번호를 암호화해야하는 이유는?
  - [x] 이에 대한 법적 근거는? 
  - [x] 암호화하지 않아서 생긴 문제는?
  - [x] 실제 사례는?
- [x] 해시함수란?
  - [x] 해시함수의 특징
- [x] 해시함수의 단점 및 취약점
  - [x] 레인보우 테이블, 레인보우 어택
  - [x] 무차별 대입 공격: 브루트포스 
  - [x] 인식 가능성
- [x] 해결방안
  - [x] 솔팅
  - [x] 키 스트레칭
  - [x] 비밀번호를 위한 해시 알고리즘 사용 
    - [x] bcrypt 설명
  - [x] 길고 복잡한 비밀번호 상용 권장
- [x] 법령에 따라 권장되는 암호화 방법 소개
- [x] 예제
  - [x] NodeJS 예제
  - [x] PHP 예제

**Comment by hsh2001** [comment]
bcrypt의 사용법은 알겠는데 자세한 속사정은 잘 모르겠습니다 ㅠㅜ 혹시 도움 주실 분 있나요?

**Comment by hsh2001** [comment]
88b027c
da3f8d0
9b669cd

`암호화란?`, `이에 대한 법적 근거는?`, `해시함수란?`,  `해시함수의 특징`, ` 해시함수의 단점 및 취약점`, ` 레인보우 테이블, 레인보우 어택`, ` 무차별 대입 공격: 브루트포스`, ` 인식 가능성`, `솔팅`, `키 스트레칭`, ` 길고 복잡한 비밀번호 상용 권장`, `NodeJS 예제`가 추가된  커밋들.

**Comment by hsh2001** [comment]
a27a327 : `bcrypt 설명`이 추가된 커밋.

직접 해결했습니다. 근데 아직 미숙해서 혹시 부족한 부분이 있다면 지적해주세요!

**Comment by hsh2001** [comment]
08d5cc4  : `PHP 예제`가 추가된 커밋.

**Comment by hsh2001** [comment]
NodeJS와 PHP의 예제가 추가되었습니다. 문법 오류나 개선 사항은 자유롭게 댓글로 남겨주세요. 다른 언어 예제를 추가해주시는 것도 대환영입니다!

**Comment by cwvv** [comment]
뿡!
